# https://github.com/NVIDIA/nvidia-container-toolkit 

version: '3.9'

services:
  ubuntu:
    environment:
      - TZ=Europe/Madrid
      - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
      - NVIDIA_VISIBLE_DEVICES=all
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
    image: ubuntu
    command: nvidia-smi
